import { PGlite } from './node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const owner='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002';
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.rotas(id uuid primary key,user_id uuid);
create table public.entregas(id uuid primary key,cliente text,endereco text,status text,observacoes text,created_at timestamptz,latitude double precision,longitude double precision,user_id uuid not null,rota_id uuid references rotas(id));
insert into auth.users values ('${owner}'),('${other}');
select set_config('request.jwt.claim.sub','${owner}',false);`);
await db.exec(await readFile(new URL('../../supabase/migrations/20261007_delivery_quota.sql',import.meta.url),'utf8'));
const row = n => ({id:`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`,endereco:`Rua ${n}`,status:'pendente'});
const add = xs => db.query('select * from public.darota_add_deliveries($1::jsonb)', [JSON.stringify(xs)]);
const used = async () => (await db.query('select public.darota_quota_status() s')).rows[0].s;
let checks=0;
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
await check('disabled migration preserves existing testers',async()=>{await add(Array.from({length:8},(_,i)=>row(i)));assert.equal((await used()).used,0);assert.equal((await used()).enforced,false);});
await db.exec(`update darota_plan_accounts set enforced=true where user_id='${owner}';`);
await check('batch over five rolls back all deliveries and usage',async()=>{await assert.rejects(add(Array.from({length:6},(_,i)=>row(i+20))),/DAROTA_QUOTA_EXCEEDED/);assert.equal((await used()).used,0);assert.equal((await db.query('select count(*)::int n from entregas')).rows[0].n,8);});
await check('exactly five succeeds',async()=>{assert.equal((await add(Array.from({length:5},(_,i)=>row(i+30)))).rows.length,5);assert.equal((await used()).used,5);});
await check('sixth delivery blocked',async()=>{await assert.rejects(add([row(40)]),/DAROTA_QUOTA_EXCEEDED/);assert.equal((await used()).used,5);});
await check('retry same ID is not charged twice',async()=>{await add([row(30)]);assert.equal((await used()).used,5);});
await check('editing and deleting do not replenish quota',async()=>{await db.exec(`update entregas set endereco='Outra rua' where id='${row(30).id}'; delete from entregas where id='${row(31).id}';`);assert.equal((await used()).used,5);});
await check('daily reset uses server date in Sao Paulo',async()=>{await db.exec(`update darota_delivery_usage set usage_day=usage_day-1;`);assert.equal((await used()).used,0);assert.equal((await used()).timezone,'America/Sao_Paulo');await add([row(41)]);assert.equal((await used()).used,1);});
await check('valid premium bypasses limit; expired premium resumes',async()=>{await db.exec(`update darota_plan_accounts set premium_until=now()+interval '1 day';`);await add(Array.from({length:6},(_,i)=>row(i+50)));assert.equal((await used()).used,1);await db.exec(`update darota_plan_accounts set premium_until=now()-interval '1 day';`);assert.equal((await used()).premium,false);});
await check('owner assigned by server regardless of supplied user_id',async()=>{await add([{...row(60),user_id:other}]);const r=await db.query('select user_id from entregas where id=$1',[row(60).id]);assert.equal(r.rows[0].user_id,owner);});
await check('foreign route rejected',async()=>{await db.exec(`insert into rotas values ('20000000-0000-4000-8000-000000000001','${other}');`);await assert.rejects(add([{...row(61),rota_id:'20000000-0000-4000-8000-000000000001'}]),/INVALID_DELIVERY/);});
await check('invalid batch rejected without consuming quota',async()=>{const before=(await used()).used;for(const bad of [null,{},42])await assert.rejects(add(bad),/INVALID_BATCH/);assert.equal((await used()).used,before);});
await check('accounts have independent counters',async()=>{await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);assert.equal((await used()).used,0);await add([row(70)]);assert.equal((await used()).used,0);});
await check('anonymous requests rejected',async()=>{await db.exec(`select set_config('request.jwt.claim.sub','',false);`);await assert.rejects(add([row(71)]),/AUTH_REQUIRED/);});
await check('clients cannot grant premium or erase usage',async()=>{await db.exec(`set role authenticated;`);await assert.rejects(db.exec(`update darota_plan_accounts set premium_until=now()+interval '1 year';`),/permission denied/);await assert.rejects(db.exec('delete from darota_delivery_usage'),/permission denied/);await db.exec('reset role;');});
console.log(`${checks} SQL checks passed`);await db.close();
